Update calculator_pipeline.yml

diff --git a/.github/workflows/calculator_pipeline.yml b/.github/workflows/calculator_pipeline.yml
--- a/.github/workflows/calculator_pipeline.yml
+++ b/.github/workflows/calculator_pipeline.yml
@@ -56,6 +56,13 @@ jobs:
         run: |
           pytest --junit-xml=report.xml
 
+      # Publish test results
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'tests/report.xml'
+
       # Create Docker image      
       - name: Build Docker image
         run: |
